export const viaRoad = [
	"Dar_es_salaam - Morogoro",
	"Dar_es_salaam - Morogoro - Iringa - Njombe - Mbeya",
	"Dar_es_salaam - Morogoro - Dodoma",
	"Dar_es_salaam - Morogoro - Mwanza",
	"Dar_es_salaam - Tanga",
	"Dar_es_salaam - Arusha",
	"Dar_es_salaam - Kilimanjaro",
	"Dar_es_salaam - Tabora",
	"Dar_es_salaam - Kigoma",
	"Dar_es_salaam - Singida",
	"Dar_es_salaam - Shinyanga",
	"Dar_es_salaam - Morogoro - Tanga",
	"Dar_es_salaam - Morogoro - Dodoma - Tabora",
	"Dar_es_salaam - Morogoro - Dodoma - Tabora - Kigoma",
	"Dar_es_salaam - Morogoro - Dodoma - Singida",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga - Geita - Kagera",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu - Manyara - Babati",
	"Dar_es_salaam - Morogoro - Dodoma - Singida - Shinyanga - Geita - Mara - Mwanza - Simiyu - Manyara - Babati - Singida",
	"Dodoma - Singida",
	"Dodoma - Singida - Manyara - Babati - Arusha",
	"Dodoma - Singida - Manyara - Babati - Arusha - Moshi - Tanga",
	"Dodoma - Singida - Manyara - Babati - Arusha - Moshi - Pangani - Tanga",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma - Mwanza",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma - Mwanza - Shinyanga",
	"Dodoma - Singida - Manyara - Babati - Arusha - Kilimanjaro - Tabora - Kigoma - Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera",
	"Mwanza - Shinyanga",
	"Mwanza - Shinyanga - Geita",
	"Mwanza - Shinyanga - Geita - Mara",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora - Singida",
	"Mwanza - Shinyanga - Geita - Mara - Simiyu - Kagera - Kigoma - Tabora - Singida - Dodoma",
];
